# Generated by Django 3.0.4 on 2020-03-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimeDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='item',
            name='director',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='監督'),
        ),
        migrations.AlterField(
            model_name='item',
            name='media',
            field=models.IntegerField(choices=[(1, 'BD'), (2, 'DVD'), (3, 'BD/DVD両方')], default=1, verbose_name='メディア形式'),
        ),
        migrations.AlterField(
            model_name='item',
            name='place',
            field=models.CharField(max_length=250, verbose_name='保管場所'),
        ),
        migrations.AlterField(
            model_name='item',
            name='production',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='制作会社'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=250, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='item',
            name='voiceactor',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='主演声優'),
        ),
    ]
